import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF006A60),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFF74F8E5),
  onPrimaryContainer: Color(0xFF00201C),
  secondary: Color(0xFF695F00),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFF4E569),
  onSecondaryContainer: Color(0xFF1F1C00),
  tertiary: Color(0xFF456179),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFCCE5FF),
  onTertiaryContainer: Color(0xFF001E31),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFAFDFB),
  onBackground: Color(0xFF191C1B),
  outline: Color(0xFF6F7977),
  onInverseSurface: Color(0xFFEFF1EF),
  inverseSurface: Color(0xFF2D3130),
  inversePrimary: Color(0xFF53DBC9),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF006A60),
  outlineVariant: Color(0xFFBEC9C6),
  scrim: Color(0xFF000000),
  surface: Color(0xFFF7FAF8),
  onSurface: Color(0xFF191C1B),
  surfaceVariant: Color(0xFFDAE5E1),
  onSurfaceVariant: Color(0xFF3F4947),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFF53DBC9),
  onPrimary: Color(0xFF003731),
  primaryContainer: Color(0xFF005048),
  onPrimaryContainer: Color(0xFF74F8E5),
  secondary: Color(0xFFD7C950),
  onSecondary: Color(0xFF363100),
  secondaryContainer: Color(0xFF4F4800),
  onSecondaryContainer: Color(0xFFF4E569),
  tertiary: Color(0xFFADCAE6),
  onTertiary: Color(0xFF153349),
  tertiaryContainer: Color(0xFF2D4961),
  onTertiaryContainer: Color(0xFFCCE5FF),
  error: Color(0xFFFFB4AB),
  errorContainer: Color(0xFF93000A),
  onError: Color(0xFF690005),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFF191C1B),
  onBackground: Color(0xFFE0E3E1),
  outline: Color(0xFF899390),
  onInverseSurface: Color(0xFF191C1B),
  inverseSurface: Color(0xFFE0E3E1),
  inversePrimary: Color(0xFF006A60),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF53DBC9),
  outlineVariant: Color(0xFF3F4947),
  scrim: Color(0xFF000000),
  surface: Color(0xFF101413),
  onSurface: Color(0xFFC4C7C5),
  surfaceVariant: Color(0xFF3F4947),
  onSurfaceVariant: Color(0xFFBEC9C6),
);

CupertinoThemeData lightCupertinoTheme = CupertinoThemeData(
  brightness: Brightness.light,
  primaryColor: lightColorScheme.primary,
  barBackgroundColor: lightColorScheme.background,
  scaffoldBackgroundColor: lightColorScheme.surface,
  textTheme: CupertinoTextThemeData(
    primaryColor: lightColorScheme.onPrimary,
  ),
);

CupertinoThemeData darkCupertinoTheme = CupertinoThemeData(
  brightness: Brightness.dark,
  primaryColor: darkColorScheme.primary,
  barBackgroundColor: darkColorScheme.background,
  scaffoldBackgroundColor: darkColorScheme.surface,
  textTheme: CupertinoTextThemeData(
    primaryColor: darkColorScheme.onPrimary,
  ),
);
